# https://starship.rs/config/

add_newline = false

[package]
disabled = true

[directory]
style = "bold blue"

[git_branch]
style = "bold #ffffff"

[git_status]
ahead = "[](purple)[$count](white)"
behind = "[](cyan)[$count](white)"
conflicted = '[=$count](yellow)'
deleted = '[✘$count](black)'
diverged = "[](cyan)[$ahead_count](white)[](purple)[$behind_count](white)"
modified = '[*$count](red)'
renamed = "[»$count](purple)"
staged = "[+$count](green)"
stashed = "[\\$$count](yellow)"
style = "bold bright-white"
untracked = "[?$count](cyan)"

[git_commit]
only_detached = true
style = "bold black"
format = "[$hash]($style) "

[ruby]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "
